commands:

  - type: download
    url:  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dst:  '<%= get_var!(:"vim.autoload_dir", type: :directory).join("plug.vim") %>'
    only: f?vim

  - type: sync
    repo: 'git@github.com:alem0lars/vim-templates'
    dst:  '<%= get_var!(:"vim.template_dirs")[0] %>'
    only: f?vim && v?vim.template_dirs

elems:

  - src:  ^(vimrc)$
    dst:  ~/.<1>
    only: f?vim && f?vanilla

  - src:  ^((?!.*vimrc).+)$
    dst:  '<%= get_var! :"vim.base_dir", type: :directory %>/<1>'
    only: f?vim


# vim: set filetype=eruby.yaml :
