commands:

  - type: download
    url:  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dst:  '<%= get_var!(:"vim.autoload_dir", type: :directory).join("plug.vim") %>'
    only:
      features:
        - vim

elems:

  - src: elems/(.+)$
    dst: '<%= get_var! :"vim.base_dir", type: :directory %>/<1>'
    only:
      features:
        - vim

# vim: set filetype=eruby.yaml :
