commands:

  - type: git_sync
    repo: https://github.com/Shougo/dein.vim
    dst:  <%= get_var!(:"vim.plugins_dir", :type => :directory).join(*%w(repos github.com Shougo dein.vim)) %>
    only:
      features:
        - neovim

elems:

  - src: elems/(.+)$
    dst: <%= xdg_config_home(:nvim) %>/<1>
    only:
      features:
        - neovim

# vim: set filetype=eruby.yaml :
